/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DasborRouteImport } from './routes/dasbor'
import { Route as GuruRouteImport } from './routes/guru'
import { Route as InputNilaiRouteImport } from './routes/input-nilai'
import { Route as KelasRouteImport } from './routes/kelas'
import { Route as MapelRouteImport } from './routes/mapel'
import { Route as NilaiSayaRouteImport } from './routes/nilai-saya'
import { Route as RaporRouteImport } from './routes/rapor'
import { Route as RekapKelasRouteImport } from './routes/rekap-kelas'
import { Route as RekapNilaiRouteImport } from './routes/rekap-nilai'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as TahunAjaranRouteImport } from './routes/tahun-ajaran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DasborRoute = DasborRouteImport.update({
  id: '/dasbor',
  path: '/dasbor',
  getParentRoute: () => rootRouteImport,
} as any)
const GuruRoute = GuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => rootRouteImport,
} as any)
const InputNilaiRoute = InputNilaiRouteImport.update({
  id: '/input-nilai',
  path: '/input-nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const KelasRoute = KelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => rootRouteImport,
} as any)
const MapelRoute = MapelRouteImport.update({
  id: '/mapel',
  path: '/mapel',
  getParentRoute: () => rootRouteImport,
} as any)
const NilaiSayaRoute = NilaiSayaRouteImport.update({
  id: '/nilai-saya',
  path: '/nilai-saya',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporRoute = RaporRouteImport.update({
  id: '/rapor',
  path: '/rapor',
  getParentRoute: () => rootRouteImport,
} as any)
const RekapKelasRoute = RekapKelasRouteImport.update({
  id: '/rekap-kelas',
  path: '/rekap-kelas',
  getParentRoute: () => rootRouteImport,
} as any)
const RekapNilaiRoute = RekapNilaiRouteImport.update({
  id: '/rekap-nilai',
  path: '/rekap-nilai',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const TahunAjaranRoute = TahunAjaranRouteImport.update({
  id: '/tahun-ajaran',
  path: '/tahun-ajaran',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dasbor': typeof DasborRoute
  '/guru': typeof GuruRoute
  '/input-nilai': typeof InputNilaiRoute
  '/kelas': typeof KelasRoute
  '/mapel': typeof MapelRoute
  '/nilai-saya': typeof NilaiSayaRoute
  '/rapor': typeof RaporRoute
  '/rekap-kelas': typeof RekapKelasRoute
  '/rekap-nilai': typeof RekapNilaiRoute
  '/siswa': typeof SiswaRoute
  '/tahun-ajaran': typeof TahunAjaranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dasbor': typeof DasborRoute
  '/guru': typeof GuruRoute
  '/input-nilai': typeof InputNilaiRoute
  '/kelas': typeof KelasRoute
  '/mapel': typeof MapelRoute
  '/nilai-saya': typeof NilaiSayaRoute
  '/rapor': typeof RaporRoute
  '/rekap-kelas': typeof RekapKelasRoute
  '/rekap-nilai': typeof RekapNilaiRoute
  '/siswa': typeof SiswaRoute
  '/tahun-ajaran': typeof TahunAjaranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dasbor': typeof DasborRoute
  '/guru': typeof GuruRoute
  '/input-nilai': typeof InputNilaiRoute
  '/kelas': typeof KelasRoute
  '/mapel': typeof MapelRoute
  '/nilai-saya': typeof NilaiSayaRoute
  '/rapor': typeof RaporRoute
  '/rekap-kelas': typeof RekapKelasRoute
  '/rekap-nilai': typeof RekapNilaiRoute
  '/siswa': typeof SiswaRoute
  '/tahun-ajaran': typeof TahunAjaranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dasbor'
    | '/guru'
    | '/input-nilai'
    | '/kelas'
    | '/mapel'
    | '/nilai-saya'
    | '/rapor'
    | '/rekap-kelas'
    | '/rekap-nilai'
    | '/siswa'
    | '/tahun-ajaran'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dasbor'
    | '/guru'
    | '/input-nilai'
    | '/kelas'
    | '/mapel'
    | '/nilai-saya'
    | '/rapor'
    | '/rekap-kelas'
    | '/rekap-nilai'
    | '/siswa'
    | '/tahun-ajaran'
  id:
    | '__root__'
    | '/'
    | '/dasbor'
    | '/guru'
    | '/input-nilai'
    | '/kelas'
    | '/mapel'
    | '/nilai-saya'
    | '/rapor'
    | '/rekap-kelas'
    | '/rekap-nilai'
    | '/siswa'
    | '/tahun-ajaran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DasborRoute: typeof DasborRoute
  GuruRoute: typeof GuruRoute
  InputNilaiRoute: typeof InputNilaiRoute
  KelasRoute: typeof KelasRoute
  MapelRoute: typeof MapelRoute
  NilaiSayaRoute: typeof NilaiSayaRoute
  RaporRoute: typeof RaporRoute
  RekapKelasRoute: typeof RekapKelasRoute
  RekapNilaiRoute: typeof RekapNilaiRoute
  SiswaRoute: typeof SiswaRoute
  TahunAjaranRoute: typeof TahunAjaranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dasbor': {
      id: '/dasbor'
      path: '/dasbor'
      fullPath: '/dasbor'
      preLoaderRoute: typeof DasborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guru': {
      id: '/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof GuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input-nilai': {
      id: '/input-nilai'
      path: '/input-nilai'
      fullPath: '/input-nilai'
      preLoaderRoute: typeof InputNilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelas': {
      id: '/kelas'
      path: '/kelas'
      fullPath: '/kelas'
      preLoaderRoute: typeof KelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapel': {
      id: '/mapel'
      path: '/mapel'
      fullPath: '/mapel'
      preLoaderRoute: typeof MapelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nilai-saya': {
      id: '/nilai-saya'
      path: '/nilai-saya'
      fullPath: '/nilai-saya'
      preLoaderRoute: typeof NilaiSayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapor': {
      id: '/rapor'
      path: '/rapor'
      fullPath: '/rapor'
      preLoaderRoute: typeof RaporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekap-kelas': {
      id: '/rekap-kelas'
      path: '/rekap-kelas'
      fullPath: '/rekap-kelas'
      preLoaderRoute: typeof RekapKelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rekap-nilai': {
      id: '/rekap-nilai'
      path: '/rekap-nilai'
      fullPath: '/rekap-nilai'
      preLoaderRoute: typeof RekapNilaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahun-ajaran': {
      id: '/tahun-ajaran'
      path: '/tahun-ajaran'
      fullPath: '/tahun-ajaran'
      preLoaderRoute: typeof TahunAjaranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DasborRoute: DasborRoute,
  GuruRoute: GuruRoute,
  InputNilaiRoute: InputNilaiRoute,
  KelasRoute: KelasRoute,
  MapelRoute: MapelRoute,
  NilaiSayaRoute: NilaiSayaRoute,
  RaporRoute: RaporRoute,
  RekapKelasRoute: RekapKelasRoute,
  RekapNilaiRoute: RekapNilaiRoute,
  SiswaRoute: SiswaRoute,
  TahunAjaranRoute: TahunAjaranRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
